### PR TITLE
Upgrade to eslint v3.13

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2017/01/eslint-v3.13.0-released

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit fe848eef164fa1c8478615d07682810f64d0a2e0 has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r=nekoya

**Comment by popuko** [comment]
:pushpin: Commit fe848eef164fa1c8478615d07682810f64d0a2e0 has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: fe848eef164fa1c8478615d07682810f64d0a2e0 has been merged into the auto branch 3259db2ec79fe1abeae971fd3fd967205a6dc0d7

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/190510510)

**Pull request merged**
