### PR TITLE
Register new owners

### PR DESCRIPTION
**Pull request by nekoya**
got it

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 9f91e50e13a13bf53557013ec7f9c972423d53b9 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 9f91e50e13a13bf53557013ec7f9c972423d53b9 has been merged into the auto branch f0b5b72de2854b25fa79c549df95acc7343e4d0d

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/265491897?utm_source=github_status&utm_medium=notification)

**Pull request merged**
