### PR TITLE
Upgrade ESLint to v3.15

### PR DESCRIPTION
**Pull request by saneyuki**
- This change enables http://eslint.org/docs/rules/template-tag-spacing.
- Fix https://github.com/voyagegroup/eslint-config-fluct/issues/69

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit df1e8973edfa1f6468ba0c29342aaf53a6e1a919 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: df1e8973edfa1f6468ba0c29342aaf53a6e1a919 has been merged into the auto branch fc8007da72f6f02ee652e546294b4f5fb18ffaa8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/201356058)

**Pull request merged**
