### PR TITLE
Update eslint-plugin-react

### PR DESCRIPTION
**Pull request by saneyuki**
https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 7dae79c0e7467f9b94641187cd5faea3ead8f72c has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 7dae79c0e7467f9b94641187cd5faea3ead8f72c has been merged into the auto branch 651fef1efecec66677e2c263c6750b79f265b6d8

**Comment by saneyuki** [comment]
@popuko r=nekoya

**Comment by popuko** [comment]
:pushpin: Commit 7dae79c0e7467f9b94641187cd5faea3ead8f72c has been approved by `saneyuki`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by saneyuki** [comment]
@popuko r=nekoya

**Comment by popuko** [comment]
:pushpin: Commit 7dae79c0e7467f9b94641187cd5faea3ead8f72c has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 7dae79c0e7467f9b94641187cd5faea3ead8f72c has been merged into the auto branch 651fef1efecec66677e2c263c6750b79f265b6d8

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/190510351)

**Pull request merged**
