### PR TITLE
Fix the typo in the setup instruction

### PR DESCRIPTION
**Pull request by saneyuki**

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 3bdbd546c3ba4cac35394e92f833615463d706e3 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 3bdbd546c3ba4cac35394e92f833615463d706e3 has been merged into the auto branch e4e2ef64b1e1ca7138f21ea86659fe90303dcd13

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/294686005?utm_source=github_status&utm_medium=notification)

**Pull request merged**
