### PR TITLE
Upgrade eslint-plugin-react to v7.0

### PR DESCRIPTION
**Pull request by saneyuki**
- This is a __BREAKING CHANGE__.
  - If you use  eslint-plugin-react, then your code may be effected by eslint-plugin-react.
- Fix https://github.com/voyagegroup/eslint-config-fluct/issues/84

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 6bdaa07b313f93d8aad805caaf4d5ad0dab1ce03 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 6bdaa07b313f93d8aad805caaf4d5ad0dab1ce03 has been merged into the auto branch 43d7effecb2f7355bb4981381adf4eae67c7e23a

**Comment by popuko** [comment]
:collision: The result of what tried to merge this pull request is `error`.

* [The Travis CI build could not complete due to an error](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/231093627?utm_source=github_status&utm_medium=notification)

**Comment by nekoya** [comment]
@popuko r+

Travis had some problem.

**Comment by popuko** [comment]
:pushpin: Commit 6bdaa07b313f93d8aad805caaf4d5ad0dab1ce03 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 6bdaa07b313f93d8aad805caaf4d5ad0dab1ce03 has been merged into the auto branch 43d7effecb2f7355bb4981381adf4eae67c7e23a

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/231351399?utm_source=github_status&utm_medium=notification)

**Pull request merged**
