### PR TITLE
Upgrade ESLInt to v5.5

### PR DESCRIPTION
**Pull request by saneyuki**
## Changelogs

* [5.3](https://eslint.org/blog/2018/08/eslint-v5.3.0-released)
* [5.4](https://eslint.org/blog/2018/08/eslint-v5.4.0-released)
* [5.5](https://eslint.org/blog/2018/08/eslint-v5.5.0-released)

## Detailed Design

This pull requests adds new rules introduced by ESLint v5.3.

### Enabled

* `no-misleading-character-class`
    * I think this should make this error.
* `no-async-promise-executor`
    * I think this should make this error.
* `require-unicode-regexp`
    * I think we should make this error.
      I wrote why we should do it as the code comment. Please see it.

### Disabled

* `require-atomic-updates`
    * I don't think this is useful because this does not (cannot) use other semantics and only uses a syntax to detect a race condition. I doubt that ECMA262 semantics and syntax are insufficiency to detect this problem correctly and it would be a flaky.
    * Please see the code comment to know the detail.

### CODE REVIEW

**Comment by saneyuki** [comment]
@kanufy ping?

**Comment by kanufy** [comment]
ああああああみます
🙏🙏🙏🙏

**Comment by saneyuki** [comment]
Thank you! It's fine whenever you have a free time.

**Comment by kanufy** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 3ac8086a7c12a7a0de3a1fae30b1c7255b8e8dc4 has been approved by `kanufy`

**Comment by popuko** [comment]
:hourglass: 3ac8086a7c12a7a0de3a1fae30b1c7255b8e8dc4 has been merged into the auto branch d2b7c8d051de6360e58f93e93ab74227e638347b

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/429923149?utm_source=github_status&utm_medium=notification)

**Pull request merged**
