### PR TITLE
Upgrade ESLint to v3.17

### PR DESCRIPTION
**Pull request by nekoya**
http://eslint.org/blog/2017/03/eslint-v3.17.0-released

new rules:

- http://eslint.org/docs/rules/no-compare-neg-zero
- http://eslint.org/docs/rules/nonblock-statement-body-position

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 7c53395be38a943ce7c53889d151b614f9000c5b has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 7c53395be38a943ce7c53889d151b614f9000c5b has been merged into the auto branch e9bf0ff3cf936f4f787dc4d7e46645ee96d82f1b

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/208085946)

**Pull request merged**
