### PR TITLE
Update ESLint v4.15

### PR DESCRIPTION
**Pull request by kanufy**
fix: #121

### CODE REVIEW

**Comment by saneyuki** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 88f75331cd4ad89813ce0e46d64bce270e8c52a2 has been approved by `saneyuki`

**Comment by popuko** [comment]
:hourglass: 88f75331cd4ad89813ce0e46d64bce270e8c52a2 has been merged into the auto branch 694263a5c65aea9477cb87d5933aa5b85a541eec

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/329746472?utm_source=github_status&utm_medium=notification)

**Pull request merged**
