### PR TITLE
Upgrade eslint-plugin-node to v4.0

### PR DESCRIPTION
**Pull request by saneyuki**
- https://github.com/mysticatea/eslint-plugin-node/releases

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit c32a6e3803f10f2ffc2d8d414ee6bc9470063b0d has been approved by `nekoya`

**Comment by popuko** [comment]
:postbox: This pull request is queued. Please await the time.

**Comment by popuko** [comment]
:hourglass: c32a6e3803f10f2ffc2d8d414ee6bc9470063b0d has been merged into the auto branch 2decd1684ca8403f942885ccb4389c7c2fc27fcd

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/201356345)

**Pull request merged**
