### PR TITLE
Enable argsIgnorePattern for no-unused-vars

### PR DESCRIPTION
**Pull request by saneyuki**
We should sort it with TypeScript compiler's builtin linter.

### CODE REVIEW

**Comment by saneyuki** [comment]
@himu62 could you review this?

And could you also review this, @nekoya ?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 65c60234eeb8b84dee87f77044161670c112eaf1 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 65c60234eeb8b84dee87f77044161670c112eaf1 has been merged into the auto branch e0dc92dd4b5fc880dfe8d7a269070eeb2a4e9fd9

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/288430704?utm_source=github_status&utm_medium=notification)

**Pull request merged**
