### PR TITLE
Upgrade eslint to v3.11.0

### PR DESCRIPTION
**Pull request by saneyuki**
## changelog

http://eslint.org/blog/2016/11/eslint-v3.11.0-released

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
Try to merge this pull request which has been approved by `nekoya`

**Pull request merged**
