### PR TITLE
Upgrade rules and dependencies to the latest

### LINKED ISSUE #104: eslint v4.2以降の変更あらためて確認する
v4.2までのrule追加は #103 でやるとしてそれ以降みる（v4.1はbug fixなのでリンクはってない）

- https://eslint.org/blog/2017/07/eslint-v4.3.0-released
- https://eslint.org/blog/2017/08/eslint-v4.4.0-released
- https://eslint.org/blog/2017/08/eslint-v4.5.0-released

#99 もあるのでそのへんも確認していこう

### PR DESCRIPTION
**Pull request by nekoya**
fix #104

### CODE REVIEW

**Comment by nekoya** [comment]
r? @himu62 

I think you are the most appropriate of the "guardian" of this repo.

What's your opinion?

**Comment by himu62** [comment]
@popuko r+

You are right. I'm the guardian.

**Comment by popuko** [comment]
:pushpin: Commit cae1bbc14982cf4449ca3e57e3e6586e5f17225a has been approved by `himu62`

**Comment by popuko** [comment]
:hourglass: cae1bbc14982cf4449ca3e57e3e6586e5f17225a has been merged into the auto branch 77515d029b557d58514d05f5b094b508c694ea1c

**Comment by saneyuki** [comment]
@himu62 

Additionally, you might need to clear the popuko's queue for this repository. I forgot the details, but @nekoya might know it.

**Comment by himu62** [comment]
popukoのしくみよくわかってなかったですmm

@nekoya さんにキュー掃除してもらったので動きましたmm

**Comment by nekoya** [comment]
I've cleaned it up now:)

**Pull request merged**
