### PR TITLE
Upgrade eslint to 3.12.

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2016/12/eslint-v3.12.0-released

### CODE REVIEW

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by popuko** [comment]
:umbrella: The latest upstream change (presumably [these](https://github.com/voyagegroup/eslint-config-fluct/compare/f047c6b72981...e35ae21d63d9)) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by saneyuki** [comment]
@nekoya r?

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
Try to merge this pull request which has been approved by `nekoya`

**Pull request merged**
