### PR TITLE
Upgrade eslint-plugin-node to v4.1

### PR DESCRIPTION
**Pull request by saneyuki**
Fix https://github.com/voyagegroup/eslint-config-fluct/issues/74

Release Note
------------

https://github.com/mysticatea/eslint-plugin-node/releases

Details
-----------

- Enable node/no-hide-core-modules
  - https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-hide-core-modules.md

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 2561d5f3ff57ff2ae5fee0ccdd67cb20cceedc4c has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 2561d5f3ff57ff2ae5fee0ccdd67cb20cceedc4c has been merged into the auto branch a19c2d94d89f1a0f601a6c6ecfa0873e5b259395

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/208080324)

**Pull request merged**
