### PR TITLE
Update eslint-plugin-react to the latest

### PR DESCRIPTION
**Pull request by saneyuki**
* This is required to update to ESLint v5.
* Please see each of commits to know details of them.

### CODE REVIEW

**Comment by kanufy** [comment]
@saneyuki r=me

**Comment by kanufy** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 8c123ef8dec216af424173638ad256347c3b7ad1 has been approved by `kanufy`

**Comment by popuko** [comment]
:hourglass: 8c123ef8dec216af424173638ad256347c3b7ad1 has been merged into the auto branch 19936170736cc0c73ccd8d4e4111695a0072a483

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/402580016?utm_source=github_status&utm_medium=notification)

**Pull request merged**
