### PR TITLE
Upgrade eslint to v3.14

### PR DESCRIPTION
**Pull request by saneyuki**
http://eslint.org/blog/2017/01/eslint-v3.14.0-released

### CODE REVIEW

**Comment by nekoya** [comment]
@popuko r+

**Comment by popuko** [comment]
:pushpin: Commit 66e2cf5d968e9a5092bf3548eb69d2e65d07d6a8 has been approved by `nekoya`

**Comment by popuko** [comment]
:hourglass: 66e2cf5d968e9a5092bf3548eb69d2e65d07d6a8 has been merged into the auto branch f04b3c294cf35a6eb190685fcdac219b5760e800

**Comment by popuko** [comment]
:tada: The result of what tried to merge this pull request is `success`.

* [The Travis CI build passed](https://travis-ci.org/voyagegroup/eslint-config-fluct/builds/194681525)

**Pull request merged**
